// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import { input as inputs, output as outputs } from "../../types";
import * as utilities from "../../utilities";

import {ObjectMeta} from "../../meta/v1";

/**
 * KubernetesEndpointResolver is the Schema for the kubernetesendpointresolver API
 */
export class KubernetesEndpointResolver extends pulumi.CustomResource {
    /**
     * Get an existing KubernetesEndpointResolver resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): KubernetesEndpointResolver {
        return new KubernetesEndpointResolver(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'kubernetes:getambassador.io/v3alpha1:KubernetesEndpointResolver';

    /**
     * Returns true if the given object is an instance of KubernetesEndpointResolver.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is KubernetesEndpointResolver {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === KubernetesEndpointResolver.__pulumiType;
    }

    public readonly apiVersion!: pulumi.Output<"getambassador.io/v3alpha1" | undefined>;
    public readonly kind!: pulumi.Output<"KubernetesEndpointResolver" | undefined>;
    public readonly metadata!: pulumi.Output<ObjectMeta | undefined>;
    /**
     * KubernetesEndpointResolver tells Ambassador to use Kubernetes Endpoints resources to resolve services. It actually has no spec other than the AmbassadorID.
     */
    public readonly spec!: pulumi.Output<outputs.getambassador.v3alpha1.KubernetesEndpointResolverSpec | undefined>;

    /**
     * Create a KubernetesEndpointResolver resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: KubernetesEndpointResolverArgs, opts?: pulumi.CustomResourceOptions) {
        let inputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            inputs["apiVersion"] = "getambassador.io/v3alpha1";
            inputs["kind"] = "KubernetesEndpointResolver";
            inputs["metadata"] = args ? args.metadata : undefined;
            inputs["spec"] = args ? args.spec : undefined;
        } else {
            inputs["apiVersion"] = undefined /*out*/;
            inputs["kind"] = undefined /*out*/;
            inputs["metadata"] = undefined /*out*/;
            inputs["spec"] = undefined /*out*/;
        }
        if (!opts.version) {
            opts = pulumi.mergeOptions(opts, { version: utilities.getVersion()});
        }
        super(KubernetesEndpointResolver.__pulumiType, name, inputs, opts);
    }
}

/**
 * The set of arguments for constructing a KubernetesEndpointResolver resource.
 */
export interface KubernetesEndpointResolverArgs {
    readonly apiVersion?: pulumi.Input<"getambassador.io/v3alpha1">;
    readonly kind?: pulumi.Input<"KubernetesEndpointResolver">;
    readonly metadata?: pulumi.Input<ObjectMeta>;
    /**
     * KubernetesEndpointResolver tells Ambassador to use Kubernetes Endpoints resources to resolve services. It actually has no spec other than the AmbassadorID.
     */
    readonly spec?: pulumi.Input<inputs.getambassador.v3alpha1.KubernetesEndpointResolverSpecArgs>;
}
