argo-cd:
  global:
    image:
      tag: v2.2.1
  dex:
    enabled: false
  configs:
    repositories:
      helm-stable-repo:
        url: https://charts.helm.sh/stable
        name: stable
        type: helm
      argo-cd-repo:
        url: https://argoproj.github.io/argo-helm
        name: argo-cd
        type: helm
